### ISSUE TITLE
unable to uninstall from stream deck

### ISSUE THREAD

**Issue by T3KKAD4N** [Cazzar/VTubeStudio-StreamDeck#11]
after having a loook and installing to my stream deck, it seems that it cant be uninstallled, when i go back to the plugin for it, it shows as install so tried installing againg to over write it then when it shows uninstall, it does nothing. not sure if it a bug but would like to be able to remove as not going to be using the vtube studio at this time. ty

**Comment by Cazzar** [comment]
This would more likely be a bug with the StreamDeck app itself, but to manually uninstall you should be able to delete the `dev.cazzar.streamdeck.vtubestudio.sdPlugin` folder from
`~/Library/Application Support/com.elgato.StreamDeck/Plugins/` (macOS) and in the folder `%appdata%\Elgato\StreamDeck\Plugins` (Windows).
