### ISSUE TITLE
Discovery port conflict with other vts plugins

### ISSUE THREAD

**Issue by xserp** [Cazzar/VTubeStudio-StreamDeck#13]
the discovery port client is not allowing to share the port with other udp clients on the same port causing other plugins to fail discovery. 
the udp client will need to allow reuse. something like: 
> _udpClient=new UdpClient();
> _udpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
This also needs to be set before binding to the port.

**Comment by Cazzar** [comment]
Version 1.3.5 has been made to fix this issue

https://github.com/Cazzar/VTubeStudio-StreamDeck/releases/tag/1.3.5
