### ISSUE TITLE
I can't figure out how to connect your plugin

### ISSUE THREAD

**Issue by Friskafist** [Cazzar/VTubeStudio-StreamDeck#38]
I've been trying to tamper with this plugin for so long and I can't get it to connect between it. I have the matching port on but I have no idea what a VTS IP is. I also followed instructions on YouTube but nothing is going the same way. I need help.

**Comment by Cazzar** [comment]
Hey! If you need more help feel free to reach out on discord, I am active on the VTubeStudio discord.

Though in terms of what "VTS IP" means in this case, is it is the IP address of the machine that is running VTubeStudio, generally if your stream deck and VTubeStudio are on the same machine `127.0.0.1` should work without an issue.

**Comment by Cazzar** [comment]
Closing this due to no recent comments indicating further issue.

If there is any problems feel free to reach out.
