### ISSUE TITLE
Send Custom Request

### ISSUE THREAD

**Issue by Kori-ko** [Cazzar/VTubeStudio-StreamDeck#5]
## Idea

As VTS's API adds additional functionality during its development and as a short-term stopgap for functionality, the option to set custom requests and see the response in the Streamdeck app as text boxes could be something worth exploring. Depending on how request/response data moves between functions this might not be feasible.

**Comment by Cazzar** [comment]
Unfortunately, with how the WebSocket stuff is coded it's not easily done, as the data is sent via structured classes.

Response wise, as they are very asynchronous so pulling that would be very hard too.

I'll leave the issue open for now though

**Comment by Cazzar** [comment]
Unfortunately without restructuring how the data is done, this isn’t really possible, though as features are requested/added I can look at adding them
